//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillerDex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillerDex.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete {0}?.
        /// </summary>
        internal static string Allies_ConfirmDelete {
            get {
                return ResourceManager.GetString("Allies_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} allies.
        /// </summary>
        internal static string Allies_Count {
            get {
                return ResourceManager.GetString("Allies_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Ally.
        /// </summary>
        internal static string Allies_PanelEdit {
            get {
                return ResourceManager.GetString("Allies_PanelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ally.
        /// </summary>
        internal static string Allies_PanelNew {
            get {
                return ResourceManager.GetString("Allies_PanelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allies.
        /// </summary>
        internal static string Allies_Title {
            get {
                return ResourceManager.GetString("Allies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the ally name!.
        /// </summary>
        internal static string Allies_ValidationName {
            get {
                return ResourceManager.GetString("Allies_ValidationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KillerDex.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Add.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑️ Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✏️ Edit.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        internal static string Dialog_ConfirmDelete {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Dialog_Success {
            get {
                return ResourceManager.GetString("Dialog_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Dialog_Warning {
            get {
                return ResourceManager.GetString("Dialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add New Match.
        /// </summary>
        internal static string Home_AddMatch {
            get {
                return ResourceManager.GetString("Home_AddMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat.
        /// </summary>
        internal static string Home_Defeat {
            get {
                return ResourceManager.GetString("Home_Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        internal static string Home_Losses {
            get {
                return ResourceManager.GetString("Home_Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches recorded.
        /// </summary>
        internal static string Home_NoMatches {
            get {
                return ResourceManager.GetString("Home_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 5 Matches.
        /// </summary>
        internal static string Home_RecentMatches {
            get {
                return ResourceManager.GetString("Home_RecentMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Statistics.
        /// </summary>
        internal static string Home_Stats {
            get {
                return ResourceManager.GetString("Home_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survivors.
        /// </summary>
        internal static string Home_Survivors {
            get {
                return ResourceManager.GetString("Home_Survivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Matches:.
        /// </summary>
        internal static string Home_TotalMatches {
            get {
                return ResourceManager.GetString("Home_TotalMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Rate:.
        /// </summary>
        internal static string Home_WinRate {
            get {
                return ResourceManager.GetString("Home_WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        internal static string Home_Wins {
            get {
                return ResourceManager.GetString("Home_Wins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Best Ally:.
        /// </summary>
        internal static string Home_BestAlly {
            get {
                return ResourceManager.GetString("Home_BestAlly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Most Faced Killer:.
        /// </summary>
        internal static string Home_MostFacedKiller {
            get {
                return ResourceManager.GetString("Home_MostFacedKiller", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string Home_NotAvailable {
            get {
                return ResourceManager.GetString("Home_NotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string Label_Alias {
            get {
                return ResourceManager.GetString("Label_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application to apply the language..
        /// </summary>
        internal static string Language_RestartRequired {
            get {
                return ResourceManager.GetString("Language_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language_Title {
            get {
                return ResourceManager.GetString("Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allies:.
        /// </summary>
        internal static string Match_Allies {
            get {
                return ResourceManager.GetString("Match_Allies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Max 3 selectable).
        /// </summary>
        internal static string Match_AlliesHint {
            get {
                return ResourceManager.GetString("Match_AlliesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select up to 3 allies!.
        /// </summary>
        internal static string Match_AlliesMax {
            get {
                return ResourceManager.GetString("Match_AlliesMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Match_Date {
            get {
                return ResourceManager.GetString("Match_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filler.
        /// </summary>
        internal static string Match_Filler {
            get {
                return ResourceManager.GetString("Match_Filler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First hook:.
        /// </summary>
        internal static string Match_FirstHook {
            get {
                return ResourceManager.GetString("Match_FirstHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generators completed:.
        /// </summary>
        internal static string Match_Generators {
            get {
                return ResourceManager.GetString("Match_Generators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killer:.
        /// </summary>
        internal static string Match_Killer {
            get {
                return ResourceManager.GetString("Match_Killer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map:.
        /// </summary>
        internal static string Match_Map {
            get {
                return ResourceManager.GetString("Match_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myself.
        /// </summary>
        internal static string Match_Myself {
            get {
                return ResourceManager.GetString("Match_Myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string Match_Notes {
            get {
                return ResourceManager.GetString("Match_Notes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add notes about this match....
        /// </summary>
        internal static string Match_NotesPlaceholder {
            get {
                return ResourceManager.GetString("Match_NotesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Match.
        /// </summary>
        internal static string Match_Save {
            get {
                return ResourceManager.GetString("Match_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match saved!.
        /// </summary>
        internal static string Match_Saved {
            get {
                return ResourceManager.GetString("Match_Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select allies....
        /// </summary>
        internal static string Match_SelectAllies {
            get {
                return ResourceManager.GetString("Match_SelectAllies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select who escaped....
        /// </summary>
        internal static string Match_SelectSurvivors {
            get {
                return ResourceManager.GetString("Match_SelectSurvivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record your Dead by Daylight match.
        /// </summary>
        internal static string Match_Subtitle {
            get {
                return ResourceManager.GetString("Match_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivors:.
        /// </summary>
        internal static string Match_Survivors {
            get {
                return ResourceManager.GetString("Match_Survivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Match.
        /// </summary>
        internal static string Match_Title {
            get {
                return ResourceManager.GetString("Match_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a killer!.
        /// </summary>
        internal static string Match_ValidationKiller {
            get {
                return ResourceManager.GetString("Match_ValidationKiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a map!.
        /// </summary>
        internal static string Match_ValidationMap {
            get {
                return ResourceManager.GetString("Match_ValidationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allies.
        /// </summary>
        internal static string Menu_Allies {
            get {
                return ResourceManager.GetString("Menu_Allies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🇬🇧 English.
        /// </summary>
        internal static string Menu_English {
            get {
                return ResourceManager.GetString("Menu_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🇮🇹 Italiano.
        /// </summary>
        internal static string Menu_Italian {
            get {
                return ResourceManager.GetString("Menu_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Menu_Manage {
            get {
                return ResourceManager.GetString("Menu_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string Menu_Maps {
            get {
                return ResourceManager.GetString("Menu_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string Search_NoResults {
            get {
                return ResourceManager.GetString("Search_NoResults", resourceCulture);
            }
        }
    }
}
