//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillerDex.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillerDex.Core.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ally with this name already exists..
        /// </summary>
        internal static string Ally_NameDuplicate {
            get {
                return ResourceManager.GetString("Ally_NameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string Ally_NameRequired {
            get {
                return ResourceManager.GetString("Ally_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A killer with this alias already exists..
        /// </summary>
        internal static string Killer_AliasDuplicate {
            get {
                return ResourceManager.GetString("Killer_AliasDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias is required..
        /// </summary>
        internal static string Killer_AliasRequired {
            get {
                return ResourceManager.GetString("Killer_AliasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A map with this name already exists..
        /// </summary>
        internal static string Map_NameDuplicate {
            get {
                return ResourceManager.GetString("Map_NameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string Map_NameRequired {
            get {
                return ResourceManager.GetString("Map_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select up to 3 allies..
        /// </summary>
        internal static string Match_AlliesMaxExceeded {
            get {
                return ResourceManager.GetString("Match_AlliesMaxExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First hook is required..
        /// </summary>
        internal static string Match_FirstHookRequired {
            get {
                return ResourceManager.GetString("Match_FirstHookRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generators completed must be between 0 and 5..
        /// </summary>
        internal static string Match_GeneratorsInvalid {
            get {
                return ResourceManager.GetString("Match_GeneratorsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killer is required..
        /// </summary>
        internal static string Match_KillerRequired {
            get {
                return ResourceManager.GetString("Match_KillerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map is required..
        /// </summary>
        internal static string Match_MapRequired {
            get {
                return ResourceManager.GetString("Match_MapRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter up to 4 survivors..
        /// </summary>
        internal static string Match_SurvivorsMaxExceeded {
            get {
                return ResourceManager.GetString("Match_SurvivorsMaxExceeded", resourceCulture);
            }
        }
    }
}
