//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillerDex.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KillerNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KillerNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillerDex.Core.Resources.KillerNames", typeof(KillerNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Artist.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Blight.
        /// </summary>
        internal static string Blight {
            get {
                return ResourceManager.GetString("Blight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cannibal.
        /// </summary>
        internal static string Cannibal {
            get {
                return ResourceManager.GetString("Cannibal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cenobite.
        /// </summary>
        internal static string Cenobite {
            get {
                return ResourceManager.GetString("Cenobite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clown.
        /// </summary>
        internal static string Clown {
            get {
                return ResourceManager.GetString("Clown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dark Lord.
        /// </summary>
        internal static string DarkLord {
            get {
                return ResourceManager.GetString("DarkLord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deathslinger.
        /// </summary>
        internal static string Deathslinger {
            get {
                return ResourceManager.GetString("Deathslinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Demogorgon.
        /// </summary>
        internal static string Demogorgon {
            get {
                return ResourceManager.GetString("Demogorgon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Doctor.
        /// </summary>
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dredge.
        /// </summary>
        internal static string Dredge {
            get {
                return ResourceManager.GetString("Dredge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Executioner.
        /// </summary>
        internal static string Executioner {
            get {
                return ResourceManager.GetString("Executioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ghost Face.
        /// </summary>
        internal static string GhostFace {
            get {
                return ResourceManager.GetString("GhostFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Good Guy.
        /// </summary>
        internal static string GoodGuy {
            get {
                return ResourceManager.GetString("GoodGuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hag.
        /// </summary>
        internal static string Hag {
            get {
                return ResourceManager.GetString("Hag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hillbilly.
        /// </summary>
        internal static string Hillbilly {
            get {
                return ResourceManager.GetString("Hillbilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Houndmaster.
        /// </summary>
        internal static string Houndmaster {
            get {
                return ResourceManager.GetString("Houndmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Huntress.
        /// </summary>
        internal static string Huntress {
            get {
                return ResourceManager.GetString("Huntress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Knight.
        /// </summary>
        internal static string Knight {
            get {
                return ResourceManager.GetString("Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Legion.
        /// </summary>
        internal static string Legion {
            get {
                return ResourceManager.GetString("Legion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lich.
        /// </summary>
        internal static string Lich {
            get {
                return ResourceManager.GetString("Lich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Mastermind.
        /// </summary>
        internal static string Mastermind {
            get {
                return ResourceManager.GetString("Mastermind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nemesis.
        /// </summary>
        internal static string Nemesis {
            get {
                return ResourceManager.GetString("Nemesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nightmare.
        /// </summary>
        internal static string Nightmare {
            get {
                return ResourceManager.GetString("Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nurse.
        /// </summary>
        internal static string Nurse {
            get {
                return ResourceManager.GetString("Nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Oni.
        /// </summary>
        internal static string Oni {
            get {
                return ResourceManager.GetString("Oni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Onryo.
        /// </summary>
        internal static string Onryo {
            get {
                return ResourceManager.GetString("Onryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pig.
        /// </summary>
        internal static string Pig {
            get {
                return ResourceManager.GetString("Pig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Plague.
        /// </summary>
        internal static string Plague {
            get {
                return ResourceManager.GetString("Plague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shape.
        /// </summary>
        internal static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Singularity.
        /// </summary>
        internal static string Singularity {
            get {
                return ResourceManager.GetString("Singularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skull Merchant.
        /// </summary>
        internal static string SkullMerchant {
            get {
                return ResourceManager.GetString("SkullMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Spirit.
        /// </summary>
        internal static string Spirit {
            get {
                return ResourceManager.GetString("Spirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trapper.
        /// </summary>
        internal static string Trapper {
            get {
                return ResourceManager.GetString("Trapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trickster.
        /// </summary>
        internal static string Trickster {
            get {
                return ResourceManager.GetString("Trickster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Twins.
        /// </summary>
        internal static string Twins {
            get {
                return ResourceManager.GetString("Twins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wraith.
        /// </summary>
        internal static string Wraith {
            get {
                return ResourceManager.GetString("Wraith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Xenomorph.
        /// </summary>
        internal static string Xenomorph {
            get {
                return ResourceManager.GetString("Xenomorph", resourceCulture);
            }
        }
    }
}
